---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-08-12T08:31:59Z"
  generation: 1
  name: kube-apiserver
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 44aff33f-57b7-4275-b99e-6bba8da0bd82
  resourceVersion: "28729"
  uid: 046c2464-3e5f-4da6-a465-dfc3f4a54472
spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-08-12T08:53:35Z"
    message: 'NodeControllerDegraded: All master nodes are ready'
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2024-08-12T08:54:15Z"
    message: 'NodeInstallerProgressing: 3 nodes are at revision 10'
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-08-12T08:50:53Z"
    message: 'StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 10'
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-12T08:34:46Z"
    message: 'KubeletMinorVersionUpgradeable: Kubelet and API server minor versions
      are synced.'
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-08-12T08:34:54Z"
    message: All is well
    reason: AsExpected
    status: "False"
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: kubeapiservers
  - group: apiextensions.k8s.io
    name: ""
    resource: customresourcedefinitions
  - group: security.openshift.io
    name: ""
    resource: securitycontextconstraints
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-kube-apiserver-operator
    resource: namespaces
  - group: ""
    name: openshift-kube-apiserver
    resource: namespaces
  - group: admissionregistration.k8s.io
    name: ""
    resource: mutatingwebhookconfigurations
  - group: admissionregistration.k8s.io
    name: ""
    resource: validatingwebhookconfigurations
  - group: controlplane.operator.openshift.io
    name: ""
    namespace: openshift-kube-apiserver
    resource: podnetworkconnectivitychecks
  - group: apiserver.openshift.io
    name: ""
    resource: apirequestcounts
  - group: config.openshift.io
    name: cluster
    resource: nodes
  versions:
  - name: raw-internal
    version: 4.17.0-0.nightly-2024-08-12-073806
  - name: kube-apiserver
    version: 1.30.3
  - name: operator
    version: 4.17.0-0.nightly-2024-08-12-073806
